mainapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('projects',views.projects,name='projects'),
    path('contact',views.contact,name='contact'),
    # path('email/', views.emailView, name='email'),
    path('success/', views.successView, name='success'),
    path("blog/",views.blog,name="blog")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
]

mainapp/models.py
from django.db import models
from datetime import datetime 
class Portfolio(models.Model):
    title=models.CharField(max_length=30,verbose_name="title")
    data=models.TextField()
    live_demo=models.URLField()
    source_code=models.URLField()
    tools=models.TextField()
    date = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.title
        

mainapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name=forms.CharField(required=True)
    from_mail = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

mainapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Portfolio
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
# import settings


def home(request):
    return render(request,'mainapp/home.html')



def about(request):
    return render(request,'mainapp/about.html')


def projects(request):
    data=Portfolio.objects.all()
    context= {
        "data": data
    }
    return render(request,'mainapp/projects.html',context)


def contact(request):
   
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        try:
            if form.is_valid():
                subject = form.cleaned_data['subject']
                name = form.cleaned_data['name']
                from_mail = form.cleaned_data['from_mail']
                message = form.cleaned_data['message']
            
                try:
                    send_mail(subject, 'Hello ' + name + ',\n'+ from_mail + ',\n' + message, from_mail, ['jyothiprakash097@gmail.com'],fail_silently=True)
                except BadHeaderError:
                    return HttpResponse('In/contactvalid header found.')
                return redirect('success')
        except:
            return HttpResponse("Mail is Not Working Properly")
    return render(request, "mainapp/contact.html", {'form': form})

    

def successView(request):
    return render(request,"mainapp/success.html")

def blog(request):
    return render(request,"mainapp/blog.html")

mainapp/templates/mainapp/about.html
{% extends "mainapp/index.html" %}

{% block content %}
<div class="about-head">About me</div>
<div class="about-container">
    <div class="about-head-1">Self Introduction</div>
    <div class="about-data">
        Hey I'm Jyothi Prakash am a Electronics & Communication Engineering Bachelor from Bharath University, 
        Chennai and working as a Python Developer at Intain,Chennai. 
        I have 6 months Experience in Python & Django experience from Intain. 
    </div>
    <div class="knowledgable">
        <p>knowledgable IN</p>
        <ul>
            <li>Python</li>
            <li>Django</li>
            <li>HTML5</li>
            <li>Css3</li>
            <li>JavaScript</li>
            <li>ReactJS</li>
            <li>Git Hub</li>
            <li>Bootstrap</li>
            <li>Sqlite3</li>
        </ul>
    </div>
    <div class="dummy">
        <a href="{% url 'home' %}" class="gohome"><i class="fas fa-long-arrow-alt-left"></i>Go Home</a>
    </div>
    <!-- <div class="gohome">Go Back</div> -->
    {% include 'mainapp/footer-icons.html' %}
    
    
</div>

{% include 'mainapp/footer.html' %}
{% endblock content %}

mainapp/templates/mainapp/blog.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
<body>
    
    <dev-widget data-username="jyothiprakash"></dev-widget>
    <script src="https://unpkg.com/dev-widget@^1/dist/card.component.min.mjs" type="module"></script>
</body>
</html> -->
{% extends "mainapp/index.html" %}

{% block content %}
<div class="blog">Blog</div>

<dev-widget data-username="jyothiprakash"></dev-widget>
    <script src="https://unpkg.com/dev-widget@^1/dist/card.component.min.mjs" type="module"></script>
    <div class="comment">
        <p>Hey guys!!! check out my blog and say hii in comments section and let's get touch with me and give some feedback so that i will learn something from you guys.</p>
    </div>
    <div class="dummy projects-margin">
        <a href="{% url 'home' %}" class="gohome"><i class="fas fa-long-arrow-alt-left"></i>Go Home</a>
    </div>
    
{% include 'mainapp/footer-icons.html' %}

{% include 'mainapp/footer.html' %}


{% endblock content %}

mainapp/templates/mainapp/contact.html
{% extends "mainapp/index.html" %}

{% block content %}
<div class="big-screen-contact"> Contact Me</div>
<div class="contact-page">
    <div class="contact-head">Contact Me</div>
    <div class="contact-1">
        {% include "mainapp/email.html" %}
    </div>
    <div class="contact-2">
        <div class="email-head">
            <p class="email color">EMAIL:</p>
            <p class="email">Jyothiprakash097@gmail.com</p>
        </div>
        <div class="telephone-head">
            <p class="telephone color">TELEPHONE</p>
            <p class="telephone">8309920412</p>
        </div>
        <div class="">
            <p class="color">Address</p>
            <p class="p">Sreenivasa nagar,</p>
            <p class="p">Chennai,</p>
            <p class="p">600073</p>
        </div>
    </div>
</div>
<div class="dummy projects-margin">
    <a href="{% url 'home' %}" class="gohome"><i class="fas fa-long-arrow-alt-left"></i>Go Home</a>
</div>
{% include 'mainapp/footer-icons.html' %}

{% include 'mainapp/footer.html' %}




{% endblock content %}

mainapp/templates/mainapp/email.html
<form method="post">
    {% csrf_token %}
    <div class="email-message">
      <label for="id_subject">Name:</label>
        {{ form.name }}
      <div class="p-element">
        <label for="id_subject">Enter Email:</label>
        {{ form.from_mail }}
        <label for="id_subject">subject:</label>
        {{ form.subject }}
      </div>
      <label for="id_subject">message:</label>
         {{ form.message }}
    </div>
    <div class="form-actions">
      <button type="submit" class="button">Send</button>
    </div>
</form>

mainapp/templates/mainapp/footer-icons.html
<div class="icons">
    <ul class="footer-icons">
        <li><a href="https://github.com/jyothiprakashk" id="profile-link"><i class="fab fa-github"></i></a></li>
            <li><a href="https://www.freecodecamp.org/jyothiprakash" alt="freecodecamp"><i class="fab fa-free-code-camp"></i></a></li>
        <li><a href="https://twitter.com/JyothiPrakashR5" alt="Twitter"><i class="fab fa-twitter"></i></a></li>
        <li><a href="https://www.linkedin.com/in/jyothiprakashk/" alt="send a mail"><i class="fab fa-linkedin-in"></i></i></a></li>
        <!-- <li><a href="#9704703078" alt="call"><i class="fa fa-phone-square" aria-hidden="true"></i></a></li> -->
        
    </ul>
</div>

mainapp/templates/mainapp/footer.html
 

<footer class="footer">
    <span>
    <i class="far fa-copyright"></i>Copyright 2020 Jyothi Prakash. All rights reserved.
    <div class="author">Coded By Jyothi Prakash</div></span>
    <!-- <div class="footer-mobile"></div> -->
</footer>

mainapp/templates/mainapp/home.html
{% extends "mainapp/index.html" %}

{% block content %}
<div class="container">
    <div>
        <div class="main-head">Jyothi Prakash Kamasani</div>
        <div class="main-head-small">A Python Web-Developer</div>
    </div>
    <div class="container-data">
        Hey I'm self-taught Python Web-Developer.Now I'm working on django backend development.I will be graduating in 
        April-2020.And currently I'm working as Python Developer Intern at <a href="https://www.in-d.ai/" id="logo">Intain Tech</a>
    </div>
    <div class="container-data-1">
        If you want to Known more about me please refer my <a href="https://github.com/jyothiprakashk">Git Hub</a> & If you have any 
        queries feel free to message me on <a href="https://twitter.com/Jyothiprakash97">Twitter</a>
    </div>
    {% include 'mainapp/footer-icons.html' %}
    {% include 'mainapp/footer.html' %}
</div>




{% endblock content %}

mainapp/templates/mainapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{%  static 'css/jp.jpeg' %}">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cyborg/bootstrap.min.css"
        integrity="sha384-mtS696VnV9qeIoC8w/PrPoRzJ5gwydRVn0oQ9b+RJOPxE1Z1jXuuJcyeNxvNZhdx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata|Kanit|Pacifico&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" type='text/css' href="{% static '/css/form.css' %}">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    {% include 'mainapp/nav_bar.html' %}
    
    
    {% block content %}

    {% endblock content %}
    <script>
        $(function(){
            $(".projects-data").hover(function() {
                  $(this).effect("shake", { times:1 }, 500);
            });
         });
    </script>
</body>
</html>

mainapp/templates/mainapp/nav_bar.html
{% load static %}
 <!-- Navbar -->
     <!--top nav-bar  -->
<div class="jp-portfolio">JP Portfolio</div>
<nav class="nav-first">
  <a class="nav-head" href="{% url 'home' %}">Jp! Portfolio</a>
    <ul>
        
        <!-- <li
        {% if 'home' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'home' %}">Home</a>
        </li> -->
        <li
        {% if 'about' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'about' %}">About</a></li
            >
           
        <li
        {% if 'projects' in request.path %}
             class="nav-item active mr-3"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'projects' %}">Projects</a></li
            >
            <li
            {% if 'blog' in request.path %}
                class="active"
              {% else %}   
                 class="nav-item mr-3"
              {% endif %}
            ><a href="{% url 'blog' %}">Blog</a></li
                >
        <li
        {% if 'contact' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'contact' %}">Contact</a></li
            >
    </ul>
</nav>    
<!-- bottom nav-bar -->
<nav class="nav-bottom">
    <ul>
        
        <li
        {% if 'about' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'about' %}"><i class="fab fa-autoprefixer li-bottom"></i></a></li
            >
           
        <li
        {% if 'projects' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'projects' %}"><i class="fas fa-project-diagram li-bottom"></i></a></li
            >
            <li
        {% if 'blog' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'blog' %}" ><i class="fab fa-blogger-b li-bottom"></i></a></li
            >
        <li
        {% if 'contact' in request.path %}
            class="active"
          {% else %}   
             class="nav-item mr-3"
          {% endif %}
        ><a href="{% url 'contact' %}"><i class="fas fa-user-circle li-bottom"></i></a></li
            >
    </ul>
</nav>

mainapp/templates/mainapp/projects.html
{% extends "mainapp/index.html" %}

{% block content %}
<div class="projects-head">Projects</div>
{% for details in data %}
    <div class="projects-data">
        <h2>{{ details.title }}</h2>
        <p> {{ details.data }}</p>
        <p><span>Tools: </span>{{ details.tools }}</p>
        <a href="{{ details.live_demo }}">Live Demo</a>
        <a href="{{ details.source_code }}" class="source-code">Source Code</a>
    </div>

{% endfor %}
<div class="dummy projects-margin">
    <a href="{% url 'home' %}" class="gohome"><i class="fas fa-long-arrow-alt-left"></i>Go Home</a>
</div>
{% include 'mainapp/footer-icons.html' %}

{% include 'mainapp/footer.html' %}


{% endblock content %}

mainapp/templates/mainapp/success.html
{% extends "mainapp/index.html" %}

{% block content %}

<div class="success">'Success! Thank you for your visiting my portfolio site and contact me.'</div>


{% endblock content %}